### ISSUE TITLE
Loading data

### ISSUE THREAD

**Issue by g-sam** [Kata-Martagon/NewsAPI#35]
Guardian data doesn't load sometimes (error: Uncaught (in promise) Error: 503
    at XMLHttpRequest.xhr.addEventListener (file:///Users/samgalson/FAC/NewsAPI/src/fetchAPI.js:9:17)

Sometimes the Guardian is taking longer -- might be nice to have some kind of loading indicator?

**Comment by matthewglover** [comment]
503 Error is the Guardian API Server not responding. Agree it would be good to add loaders, but run out of time.
