### ISSUE TITLE
Stray </div> tag

### ISSUE THREAD

**Issue by msmichellegar** [Kata-Martagon/NewsAPI#41]
I believe you have an extra `</div>` tag in your index.html.

Here: https://github.com/Kata-Martagon/NewsAPI/blob/master/index.html#L20

**Comment by nogainbar** [comment]
done! thanx! :)

**Comment by msmichellegar** [comment]
Perf! 🎉 

Try not to close other people's issues though, as whoever raised it should review the changes first ;)
