### ISSUE TITLE
ES6 features

### ISSUE THREAD

**Issue by oturnermajor** [Kata-Martagon/NewsAPI#44]
Nice to see that you've used ES6 features like promises and string templates - if you haven't already, please do make sure that everyone in your group knows how they work and is comfortable using them :)

Also go for consistency if possible. If you're going to use `const` and `let` then use them exclusively and avoid using `var`.

**Comment by matthewglover** [comment]
Thanks - we've run through all code as a group, so everyone is at least familiar with it. 

Have just searched and we don't have any `var` refs in our code (just in libs)

**Comment by oturnermajor** [comment]
Oh sorry I thought I saw some, maybe it was another group's code. Nice one, closing the issue.
